title: "Justice Rose"
name: "Justice Rose"
description: "Portfolio, Projects, and CV"
locale: "en-US"

# MUST match repo name EXACTLY
baseurl: "/fa25-portfolio-jr2368"
url: "https://yourusername.github.io"

theme: null
color_scheme: light

sass:
  style: compressed

markdown: kramdown
kramdown:
  input: GFM

# ------------------------------------
# Collections
# ------------------------------------
collections:
  projects:
    output: true
    permalink: /projects/:name/

# ------------------------------------
# Make _pages work
# ------------------------------------
defaults:
  - scope:
      path: "_pages"
    values:
      layout: default

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# ------------------------------------
# Navigation
# ------------------------------------
nav:
  - name: "Home"
    link: "{{ site.baseurl }}/"
  - name: "Projects"
    link: "{{ site.baseurl }}/projects/"
  - name: "Resume"
    link: "{{ site.baseurl }}/cv/"
